import { v4 as uuidv4 } from "uuid";

export const prendas = [
  //REMERAS//
  {
    id: uuidv4(),
    titulo: "REMERA LISA",
    imgs: "../prenda.jpeg",
    articulo: "131",
    descripcion: "",
    material: "JERSEY",
    talles: "S M L XL XXL",
    color: [
      "BLACK",
      "BLUE",
      "#7D6608",
      "#013619 ",
      "#370301",
      "#53B981",
      "#F1948A",
    ],
  },
  {
    id: uuidv4(),
    titulo: "REMERA PANAL",
    imgs: "../prenda.jpeg",
    articulo: "143",
    descripcion: "",
    material: "JERSEY",
    talles: "S M L XL XXL",
    color: ["BLACK", "#AC9C7D", "#A6ACAF"],
  },
  {
    id: uuidv4(),
    titulo: "REMERA C/CARTERA PANAL",
    imgs: "../prenda.jpeg",
    articulo: "144",
    descripcion: "",
    material: "JERSEY",
    talles: "S M L XL XXL",
    color: ["BLACK", "#AC9C7D", "#A6ACAF"],
  },

  //CHOMBAS LISAS//

  {
    id: uuidv4(),
    titulo: "CHOMBA LIZA C/VIVO",
    imgs: "../prenda.jpeg",
    articulo: "150",
    descripcion: "",
    material: "JERSEY",
    talles: "S M L XL XXL",
    color: ["BLACK", "BLUE", "#00FBFF", "#013619 ", "#FFE800"],
  },
  {
    id: uuidv4(),
    titulo: "",
    imgs: "../prenda.jpeg",
    articulo: "151",
    descripcion: "",
    material: "",
    talles: "S M L XL XXL",
    color: ["", "", "", ""],
  },
  {
    id: uuidv4(),
    titulo: "",
    imgs: "../prenda.jpeg",
    articulo: "152",
    descripcion: "",
    material: "",
    talles: "S M L XL XXL",
    color: ["", "", "", ""],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA 1/2 CIERRE",
    imgs: "../prenda.jpeg",
    articulo: "153",
    descripcion: "",
    material: "OTTOMAN",
    talles: "S M L XL XXL",
    color: ["BLACK", ""],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA LISA",
    imgs: "../prenda.jpeg",
    articulo: "154",
    descripcion: "",
    material: "JERSEY SNOWDON",
    talles: "S M L XL XXL",
    color: ["BLACK", "BLUE", "#370301", "GREEN"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA LISA",
    imgs: "../prenda.jpeg",
    articulo: "155",
    descripcion: "",
    material: "JERSEY ARTIZAN",
    talles: "S M L XL XXL",
    color: ["BLACK", "BLUE", "#013619 ", "#CDB370", "#2A2004"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA 1/2 CIERRE",
    imgs: "../prenda.jpeg",
    articulo: "156",
    descripcion: "",
    material: "JERSEY FREEDOM",
    talles: "S M L XL XXL",
    color: ["BLACK", "BLUE", "#2A2A2A", "#225E06"],
  },

  // CHOMBAS RAYADA//

  {
    id: uuidv4(),
    titulo: "CHOMBA RAYDA 24/1",
    imgs: ["../prenda.jpeg", "../prenda1.jpeg", "../prenda.jpeg"],
    articulo: "201",
    descripcion: "",
    material: "JERSEY",
    talles: "S M L XL XXL",
    color: "WHITE",
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYDA 24/1",
    imgs: "../prenda.jpeg",
    articulo: "202",
    descripcion: "",
    material: "JERSEY",
    talles: "S M L XL XXL",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYDA 24/1",
    imgs: ["../prenda.jpeg", "../prenda1.jpeg", "../prenda.jpeg"],
    articulo: "203",
    descripcion: "",
    material: "JERSEY",
    talles: "S M L XL XXL",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYDA 24/1",
    imgs: "../prenda.jpeg",
    articulo: "204",
    descripcion: "",
    material: "JERSEY",
    talles: "S M L XL XXL",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
];
