import { v4 as uuidv4 } from "uuid";

export const prendas = [
  //REMERAS//
  {
    id: uuidv4(),
    titulo: "REMERA LISA",
    categoriaId:"remera",
    imgs: "../prenda.jpeg",
    articulo: "131",
    descripcion: "",
    material: "JERSEY",
    color: [
      "BLACK",
      "BLUE",
      "#7D6608",
      "#013619 ",
      "#370301",
      "#53B981",
      "#F1948A",
    ],
  },
  {
    id: uuidv4(),
    titulo: "REMERA PANAL",
    categoriaId:"remera",
    imgs: "../prenda.jpeg",
    articulo: "143",
    descripcion: "",
    material: "JERSEY",
    color: ["BLACK", "#AC9C7D", "#A6ACAF"],
  },
  {
    id: uuidv4(),
    titulo: "REMERA",
    categoriaId:"remera",
    imgs: "../prenda.jpeg",
    articulo: "144",
    descripcion: "REMERA CON CARTERA PANAL",
    material: "JERSEY",
    color: ["BLACK", "#AC9C7D", "#A6ACAF"],
  },

  //CHOMBAS LISAS//

  {
    id: uuidv4(),
    titulo: "CHOMBA LISA",
    categoriaId:"chomba",
    imgs: "../prenda.jpeg",
    articulo: "150",
    descripcion: "CHOMBA LISA CON CUELLO VIVO",
    material: "JERSEY",
    color: ["BLACK", "BLUE", "#00FBFF", "#013619 ", "#FFE800"],
  },
  {
    id: uuidv4(),
    titulo: "",
    categoriaId:"chomba",
    imgs: "../prenda.jpeg",
    articulo: "151",
    descripcion: "",
    material: "",
    color: ["", "", "", ""],
  },
  {
    id: uuidv4(),
    titulo: "",
    categoriaId:"chomba",
    imgs: "../prenda.jpeg",
    articulo: "152",
    descripcion: "",
    material: "",
    color: ["", "", "", ""],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA 1/2 CIERRE",
    categoriaId:"chomba",
    imgs: "../prenda.jpeg",
    articulo: "153",
    descripcion: "",
    material: "OTTOMAN",
    color: ["BLACK", ""],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA LISA",
    categoriaId:"chomba",
    imgs: "../prenda.jpeg",
    articulo: "154",
    descripcion: "",
    material: "JERSEY SNOWDON",
    color: ["BLACK", "BLUE", "#370301", "GREEN"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA LISA",
    categoriaId:"chomba",
    imgs: "../prenda.jpeg",
    articulo: "155",
    descripcion: "",
    material: "JERSEY ARTIZAN",
    color: ["BLACK", "BLUE", "#013619 ", "#CDB370", "#2A2004"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA 1/2 CIERRE",
    categoriaId:"chomba",
    imgs: "../prenda.jpeg",
    articulo: "156",
    descripcion: "",
    material: "JERSEY FREEDOM",
    color: ["BLACK", "BLUE", "#2A2A2A", "#225E06"],
  },

  // CHOMBAS RAYADA//

  {
    id: uuidv4(),
    titulo: "CHOMBA RAYADA 24/1",
    categoriaId:"rayada",
    imgs: ["../prenda.jpeg", "../prenda1.jpeg", "../prenda.jpeg"],
    articulo: "201",
    descripcion: "",
    material: "JERSEY",
    paleta: "WHITE",
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYADA 24/1",
    categoriaId:"rayada",
    imgs: "../prenda.jpeg",
    articulo: "202",
    descripcion: "",
    material: "JERSEY",
    paleta: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYADA 24/1",
    categoriaId:"rayada",
    imgs: ["../prenda.jpeg", "../prenda1.jpeg", "../prenda.jpeg"],
    articulo: "203",
    descripcion: "",
    material: "JERSEY",
    paleta: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYADA 24/1",
    categoriaId:"rayada",
    imgs: "../prenda.jpeg",
    articulo: "204",
    descripcion: "",
    material: "JERSEY",
    paleta: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  //CHOMBAS RAYADAS JERSEY DOBLE//
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYADA",
    categoriaId:"doble",
    imgs: "../prenda.jpeg",
    articulo: "207",
    descripcion: "",
    material: "JERSEY DOBLE",
    paleta: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYADA",
    categoriaId:"doble",
    imgs: "../prenda.jpeg",
    articulo: "208",
    descripcion: "",
    material: "JERSEY DOBLE",
    paleta: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYADA ",
    categoriaId:"doble",
    imgs: "../prenda.jpeg",
    articulo: "209",
    descripcion: "",
    material: "JERSEY DOBLE",
    paleta: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },

  //CHOMBA PIQUE RAYADO//

  {
    id: uuidv4(),
    titulo: "CHOMBA RAYADA",
    categoriaId:"rayada",
    imgs: "../prenda.jpeg",
    articulo: "204",
    descripcion: "",
    material: "PIQUE",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },

  //FRIZA//

  {
    id: uuidv4(),
    titulo: "MEDIO CIERRE",
    categoriaId:"friza",
    imgs: "../prenda.jpeg",
    articulo: "431",
    descripcion: "CUELLO RAYADO SIN BOLSILLO",
    material: "FRIZA",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "MEDIO CIERRE ",
    categoriaId:"friza",
    imgs: "../prenda.jpeg",
    articulo: "434",
    descripcion: "",
    material: "FRIZA ESTAMPADA",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "BUZO",
    categoriaId:"friza",
    imgs: "../prenda.jpeg",
    articulo: "435",
    descripcion: "BUZO CUELLO ALTO CON BOTONES",
    material: "FRIZA SNOW",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CAMPERA",
    categoriaId:"friza",
    imgs: "../prenda.jpeg",
    articulo: "470",
    descripcion:"CAMPERA UNIVERSITARIA",
    material: "FRIZA",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CAMPERA GAMUZADA",
    categoriaId:"friza",
    imgs: "../prenda.jpeg",
    articulo: "471",
    descripcion: "CAMPERA GAMUZADA ESTAMPADA",
    material: "FRIZA",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CAMPERA C/CAPUCHA",
    categoriaId:"friza",
    imgs: "../prenda.jpeg",
    articulo: "472",
    descripcion: "CAMPERA CON CAPUCHA LISO",
    material: "FRIZA",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA FRIZA",
    categoriaId:"friza",
    imgs: "../prenda.jpeg",
    articulo: "473",
    descripcion: "",
    material: "FRIZA",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CAMPERA ESTAMPADA",
    categoriaId:"friza",
    imgs: "../prenda.jpeg",
    articulo: "474",
    descripcion: "",
    material: "FRIZA",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CAMPERA ESCOCESA",
    categoriaId:"friza",
    imgs: "../prenda.jpeg",
    articulo: "475",
    descripcion: "CAMPERA ESTILO ESCOCESA",
    material: "FRIZA",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CAMPERA ESTAMPADA",
    categoriaId:"friza",
    imgs: "../prenda.jpeg",
    articulo: "476",
    descripcion: "",
    material: "FRIZA",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CAMPERA",
    categoriaId:"friza",
    imgs: "../prenda.jpeg",
    articulo: "478",
    descripcion: "CAMPERA CUELLO BAJO",
    material: "MATELASSE BRICK",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CAMPERA",
    categoriaId:"friza",
    imgs: "../prenda.jpeg",
    articulo: "479",
    descripcion: "CAMPERA CON CUELLO INTERIOR CONTRATONO",
    material: "FRIZA",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CAMPERA",
    categoriaId:"friza",
    imgs: "../prenda.jpeg",
    articulo: "480",
    descripcion: "CAMPERA CUELLO ALTO",
    material: "MATELASSE BRICK",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "BUZO",
    categoriaId:"friza",
    imgs: "../prenda.jpeg",
    articulo: "601",
    descripcion: "BUZO CUELLO REDONDO CUADRILLE",
    material: "FRIZA",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "BUZO LISO",
    categoriaId:"friza",
    imgs: "../prenda.jpeg",
    articulo: "602",
    descripcion: "BUZO CUELLO REDONDO LISO",
    material: "FRIZA",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "JOGGUIN",
    categoriaId:"friza",
    imgs: "../prenda.jpeg",
    articulo: "608",
    descripcion: "PANTALON JOGGUIN SEMI-RECTO",
    material: "FRIZA",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },

  //POLAR//
  {
    id: uuidv4(),
    titulo: "POLAR",
    categoriaId:"polar",
    imgs: "../prenda.jpeg",
    articulo: "501",
    descripcion: "POLAR MEDIO CIERRE",
    material: "POLAR",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CAMPERA",
    categoriaId:"polar",
    imgs: "../prenda.jpeg",
    articulo: "502",
    descripcion: "CAMPERA LISA POLAR",
    material: "POLAR",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CAMPEARA",
    categoriaId:"polar",
    imgs: "../prenda.jpeg",
    articulo: "504",
    descripcion: "CAMPERA CUADRILLE",
    material: "POLAR",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CHALECO",
    categoriaId:"polar",
    imgs: "../prenda.jpeg",
    articulo: "505",
    descripcion: "",
    material: "POLAR",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },

  //PUNTO//

  {
    id: uuidv4(),
    titulo: "SWEETER",
    categoriaId:"punto",
    imgs: "../prenda.jpeg",
    articulo: "101",
    descripcion: "SWEETER CUELLO REDONDO",
    material: "PERLE",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYDA 24/1",
    categoriaId:"punto",
    imgs: "../prenda.jpeg",
    articulo: "110",
    descripcion: "",
    material: "SOFIA",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYDA 24/1",
    categoriaId:"punto",
    imgs: "../prenda.jpeg",
    articulo: "111",
    descripcion: "",
    material: "JERSEY",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYDA 24/1",
    categoriaId:"punto",
    imgs: "../prenda.jpeg",
    articulo: "115",
    descripcion: "",
    material: "JERSEY",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYDA 24/1",
    categoriaId:"punto",
    imgs: "../prenda.jpeg",
    articulo: "116",
    descripcion: "",
    material: "JERSEY",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYDA 24/1",
    categoriaId:"punto",
    imgs: "../prenda.jpeg",
    articulo: "120",
    descripcion: "",
    material: "JERSEY",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYDA 24/1",
    categoriaId:"punto",
    imgs: "../prenda.jpeg",
    articulo: "121",
    descripcion: "",
    material: "JERSEY",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYDA 24/1",
    categoriaId:"punto",
    imgs: "../prenda.jpeg",
    articulo: "301",
    descripcion: "",
    material: "JERSEY",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYDA 24/1",
    categoriaId:"punto",
    imgs: "../prenda.jpeg",
    articulo: "",
    descripcion: "",
    material: "JERSEY",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYDA 24/1",
    categoriaId:"punto",
    imgs: "../prenda.jpeg",
    articulo: "321",
    descripcion: "",
    material: "JERSEY",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYDA 24/1",
    categoriaId:"punto",
    imgs: "../prenda.jpeg",
    articulo: "831",
    descripcion: "",
    material: "JERSEY",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYDA 24/1",
    categoriaId:"punto",
    imgs: "../prenda.jpeg",
    articulo: "840",
    descripcion: "",
    material: "JERSEY",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYDA 24/1",
    categoriaId:"punto",
    imgs: "../prenda.jpeg",
    articulo: "845",
    descripcion: "",
    material: "JERSEY",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYDA 24/1",
    categoriaId:"punto",
    imgs: "../prenda.jpeg",
    articulo: "921",
    descripcion: "",
    material: "JERSEY",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYDA 24/1",
    categoriaId:"punto",
    imgs: "../prenda.jpeg",
    articulo: "931",
    descripcion: "",
    material: "JERSEY",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
  {
    id: uuidv4(),
    titulo: "CHOMBA RAYDA 24/1",
    categoriaId:"punto",
    imgs: "../prenda.jpeg",
    articulo: "932",
    descripcion: "",
    material: "JERSEY",
    color: ["WHITE", "BLACK", "BLUE", "MOSTAZA"],
  },
];
